name: ARM

on:
  push:
    branches:
    - action-testing-arm
  

jobs:
  armv7:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: uraimo/run-on-arch-action@v1.0.8
        id: runcmd
        with:
          architecture: armv7
          distribution: ubuntu18.04
          run: |
            apt-get update
            apt-get install -y curl
            curl -sSL https://get.haskellstack.org/ | sh
            stack test --haddock --no-haddock-deps --allow-different-user --compiler ghc-8.6.3
