name: Standard

on:
  push:
    branches:
    - master
    - stable
    - rc/*
    - action-testing # FIXME remove
  pull_request: {}
  

jobs:
  Style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Style
        run: |
          ./etc/scripts/get-hlint.sh
          export PATH="$(pwd)"/hlint:$PATH
          hlint src/
          hlint src/ --cpp-define=WINDOWS=1
          hlint test/ --cpp-simple

  MultiGHC:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: ["ghc-8.4", "ghc-8.6", "ghc-8.8"]
        include:
          - target: ghc-8.4
            stack_yaml: stack-ghc-84.yaml
          - target: ghc-8.6
            stack_yaml: stack-ghc-86.yaml
          - target: ghc-8.8
            stack_yaml: stack-ghc-88.yaml

    steps:
      - uses: actions/checkout@v2

      - name: Cache .stack-root
        uses: actions/cache@v1
        env:
          cache-name: stack-root
        with:
          path: .stack-root
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles(matrix.stack_yaml) }}

      - name: Test
        run: |
          set -ex
          export STACK_ROOT=$(pwd)/.stack-root
          curl -sSL https://get.haskellstack.org/ | sh -s - -f
          stack --stack-yaml ${{ matrix.stack_yaml }} test --haddock --no-haddock-deps

  Linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache .stack-root
        uses: actions/cache@v1
        env:
          cache-name: stack-root
        with:
          path: .stack-root
          key: ${{ runner.os }}-static-build-${{ env.cache-name }}-${{ hashFiles('stack.yaml') }}

      - name: Install Nix
        run: |
          (for i in {1..5}; do bash <(curl https://nixos.org/nix/install) && exit 0; done; exit 1)
          . ~/.nix-profile/etc/profile.d/nix.sh
          nix-channel --add https://nixos.org/channels/nixos-19.09 nixpkgs
          nix-channel --update # Get GHC 8.2.2

      - name: Test
        run: |
          set -ex
          export STACK_ROOT=$(pwd)/.stack-root
          curl -sSL https://get.haskellstack.org/ | sh -s - -f

          . ~/.nix-profile/etc/profile.d/nix.sh

          ALPINE_IMAGE=fpco/alpine-haskell-stack@sha256:49e7e15f3b1d3f882ba5bb701463b1d508fbf40e5aafce6ea31acd210da570ba
          stack etc/scripts/release.hs check --alpine $ALPINE_IMAGE
          stack etc/scripts/release.hs build --alpine $ALPINE_IMAGE

      - uses: actions/upload-artifact@v1
        with:
          name: linux
          path: _release

  MacOS:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache .stack-root
        uses: actions/cache@v1
        env:
          cache-name: stack-root
        with:
          path: .stack-root
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('stack.yaml') }}

      - name: Test
        run: |
          set -ex
          export STACK_ROOT=$(pwd)/.stack-root
          curl -sSL https://get.haskellstack.org/ | sh -s - -f
          stack etc/scripts/release.hs check
          stack etc/scripts/release.hs build

      - uses: actions/upload-artifact@v1
        with:
          name: macos
          path: _release

  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache .stack-root
        uses: actions/cache@v1
        env:
          cache-name: stack-root
        with:
          path: .stack-root
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('stack.yaml') }}

      - name: Install NSIS
        shell: pwsh
        run: |
          choco install nsis-unicode -y

      - name: Test
        shell: bash
        run: |
          export STACK_ROOT=$(pwd)/.stack-root
          curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
          unzip -o /usr/bin/stack.zip -d /usr/bin/
          stack etc/scripts/release.hs check
          stack etc/scripts/release.hs build

      - uses: actions/upload-artifact@v1
        with:
          name: windows
          path: _release
