name: Standard

on:
  push:
    branches:
    - master
    - stable
    - rc/*
    - action-testing # FIXME remove
  pull_request: {}
  

jobs:
  Style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Style
        run: |
          ./etc/scripts/get-hlint.sh
          export PATH="$(pwd)"/hlint:$PATH
          hlint src/
          hlint src/ --cpp-define=WINDOWS=1
          hlint test/ --cpp-simple

  Linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - stack_yaml: stack.yaml
            image: docker.pkg.github.com/commercialhaskell/stack/base-alpine:ce38a8b17b8aeeb95f03833c6d3c1623b0312fee
            stack_args: --flag stack:static
          - stack_yaml: stack-ghc-84.yaml
            image: docker.pkg.github.com/commercialhaskell/stack/base-linux-ghc84:88105b82ccfdb26b8ec0a64b316c3a943a67befa
            stack_args: ""
          - stack_yaml: stack-ghc-86.yaml
            image: docker.pkg.github.com/commercialhaskell/stack/base-linux-ghc86:f94bba6fcf3a5016b54b6048f7203ad83fd1c1a3
            stack_args: --pedantic
          - stack_yaml: stack-ghc-88.yaml
            image: docker.pkg.github.com/commercialhaskell/stack/base-linux-ghc88:f94bba6fcf3a5016b54b6048f7203ad83fd1c1a3
            stack_args: ""

    steps:
      - uses: actions/checkout@v2

      - name: Log into Github registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Test
        run: |
          docker run -v $(pwd):/src "${{ matrix.target.image }}" stack --stack-yaml "/src/${{ matrix.target.stack_yaml }}" test --haddock --no-haddock-deps ${{ matrix.target.stack_args }} --allow-different-user

  MacOS:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache .stack-root
        uses: actions/cache@v1
        env:
          cache-name: stack-root
        with:
          path: .stack-root
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('stack.yaml') }}

      - name: Test
        run: |
          export STACK_ROOT=$(pwd)/.stack-root
          curl -sSL https://get.haskellstack.org/ | sh
          stack test --haddock --no-haddock-deps

  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache .stack-root
        uses: actions/cache@v1
        env:
          cache-name: stack-root
        with:
          path: .stack-root
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('stack.yaml') }}

      - name: Test
        run: |
          export STACK_ROOT=$(pwd)/.stack-root
          curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
          unzip -o /usr/bin/stack.zip -d /usr/bin/
          stack test --haddock --no-haddock-deps
