name: Standard

on:
  push:
    branches:
    - master
    - stable
    - rc/*
    - action-testing # FIXME remove
  pull_request: {}
  

jobs:
  Style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Style
        run: |
          ./etc/scripts/get-hlint.sh
          export PATH="$(pwd)"/hlint:$PATH
          hlint src/
          hlint src/ --cpp-define=WINDOWS=1
          hlint test/ --cpp-simple

  Linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: ["Alpine", "GHC 8.4", "GHC 8.6", "GHC 8.8"]
        include:
          - target: Alpine
            stack_yaml: stack.yaml
            image: docker.pkg.github.com/commercialhaskell/stack/base-alpine:df1f913791018a881a0dc3c3e74e6222b42047d4
            stack_args: --flag stack:static --ghc-options -fsplit-sections
          - target: GHC 8.4
            stack_yaml: stack-ghc-84.yaml
            image: docker.pkg.github.com/commercialhaskell/stack/base-linux-ghc84:88105b82ccfdb26b8ec0a64b316c3a943a67befa
            stack_args: ""
          - target: GHC 8.6
            stack_yaml: stack-ghc-86.yaml
            image: docker.pkg.github.com/commercialhaskell/stack/base-linux-ghc86:f94bba6fcf3a5016b54b6048f7203ad83fd1c1a3
            stack_args: --pedantic
          - target: GHC 8.8
            stack_yaml: stack-ghc-88.yaml
            image: docker.pkg.github.com/commercialhaskell/stack/base-linux-ghc88:f94bba6fcf3a5016b54b6048f7203ad83fd1c1a3
            stack_args: ""

    steps:
      - uses: actions/checkout@v2

      - name: Log into Github registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Test
        run: |
          mkdir -p _release/bin
          docker run -v $(pwd):/src "${{ matrix.image }}" stack --stack-yaml "/src/${{ matrix.stack_yaml }}" test --haddock --no-haddock-deps ${{ matrix.stack_args }} --allow-different-user --copy-bins --local-bin-path /src/_release/bin

      - uses: actions/upload-artifact@v1
        with:
          name: binary
          path: _release/bin/stack

  MacOS:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache .stack-root
        uses: actions/cache@v1
        env:
          cache-name: stack-root
        with:
          path: .stack-root
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('stack.yaml') }}

      - name: Test
        run: |
          export STACK_ROOT=$(pwd)/.stack-root
          curl -sSL https://get.haskellstack.org/ | sh
          stack test --haddock --no-haddock-deps --local-bin-path _release/bin --copy-bins

      - uses: actions/upload-artifact@v1
        with:
          name: binary
          path: _release/bin/stack

  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache .stack-root
        uses: actions/cache@v1
        env:
          cache-name: stack-root
        with:
          path: .stack-root
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('stack.yaml') }}

      - name: Test
        shell: bash
        run: |
          export STACK_ROOT=$(pwd)/.stack-root
          curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
          unzip -o /usr/bin/stack.zip -d /usr/bin/
          stack test --haddock --no-haddock-deps --local-bin-path _release/bin --copy-bins

      - uses: actions/upload-artifact@v1
        with:
          name: binary
          path: _release/bin/stack.exe
